[build]
builder = "NIXPACKS"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "api"
source = "api/"

[services.variables]
PORT = "8000"
DATABASE_URL = "${{Postgres.DATABASE_URL}}"
CORS_ORIGINS = "https://*.vercel.app,http://localhost:3000"

[[services]]
name = "postgres"
source = "postgres:15"